name: Build && Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/setup-compose-action@v1
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: 'sbt'

    - name: Bootup Docker Compose
      run:  docker compose -f docker/docker-compose.yml -d up redis valkey

    - name: Run tests
      run: sbt "test;integration-tests/test"
