name: Build && Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker-compose:
        image: docker/compose:1.29.2
        options: --entrypoint ""
        ports:
          - 5432:5432
          - 6379:6379
          - 6380:6380

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: 'sbt'

    - name: Bootup Docker Compose
      run:  docker compose -f docker/docker-compose.yml -d up redis valkey

    - name: Run tests
      run: sbt "test;integration-tests/test"
